### ISSUE TITLE
Failed to load the easy-motion-redux package

### ISSUE THREAD

**Issue by pabloborges** [leny/atom-easy-motion-redux#14]
It happens as soon as I open Atom

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux) package, v1.1.1
### Stack Trace

Failed to load the easy-motion-redux package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/pborges/.atom/packages/easy-motion-redux/lib/views/input.js:17:26)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/pborges/.atom/packages/easy-motion-redux/lib/main.js:3:43)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "relative-numbers"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "easy-motion-redux": {
    "replaceCharacters": "abcdefghijklmnopqrstuvwxyz"
  }
}
```
### Installed Packages

``` coffee
# User
atom-dark-fusion-syntax, v1.1.0
atomatigit, v1.5.5
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autoupdate-packages, v1.3.1
easy-motion-redux, v1.1.1
environment, v1.2.0
file-icons, v1.7.13
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-diff, v0.4.0
linter, v1.11.4
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
merge-conflicts, v1.4.4
nucleus-dark-ui, v0.8.2
project-plus, v0.9.0
proton-mode, v0.10.1
recent-files-fuzzy-finder, v0.2.4
release-notes, v0.53.0
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
vim-mode-plus, v0.44.0
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by wabilin** [comment]
Hello @pabloborges
Thank you for reporting.

May I ask did you install this package from apm or git repo?

**Comment by pabloborges** [comment]
Hi @wabilin, I installed it from apm.

**Comment by wabilin** [comment]
@pabloborges 
Please update this package to latest version and run `Update Package Dependencies: Update` in atom.

**Comment by pabloborges** [comment]
I uninstalled the package long ago. I installed it today and I can't see the issue after restarting Atom.

**Comment by wabilin** [comment]
Thanks.
