### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by reem** [leny/atom-easy-motion-redux#19]
Really sorry but I'm not really sure what I was doing when this happened, maybe this is helpful anyway. Feel free to close if not.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.1
**Thrown From**: [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux) package 1.1.1

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/reem/.atom/packages/easy-motion-redux/lib/views/input.js:150

TypeError: Cannot read property '0' of undefined
    at InputView.confirm (/packages/easy-motion-redux/lib/views/input.js:150:41)
    at InputView.filterPositions (/packages/easy-motion-redux/lib/views/input.js:176:18)
    at InputView.autosubmit (/packages/easy-motion-redux/lib/views/input.js:117:14)
```

### Commands

```
     -0:19.1.0 proton:chain (input.hidden-input)
     -0:19.1.0 window:focus-pane-on-right (atom-pane.pane.active)
     -0:18.6.0 proton:toggle (input.hidden-input)
     -0:18.4.0 proton:chain (input.hidden-input)
     -0:18.4.0 window:focus-pane-on-left (atom-pane.pane.active)
     -0:17.8.0 proton:toggle (input.hidden-input)
     -0:17.6.0 proton:chain (input.hidden-input)
     -0:17.6.0 window:focus-pane-on-right (atom-pane.pane.active)
     -0:17.1.0 proton:toggle (input.hidden-input)
     -0:16.9.0 proton:chain (input.hidden-input)
     -0:16.9.0 window:focus-pane-on-left (atom-pane.pane.active)
     -0:16.7.0 vim-mode-plus:move-right (input.hidden-input)
     -0:16.5.0 proton:toggle (input.hidden-input)
     -0:16.4.0 proton:chain (input.hidden-input)
     -0:16.4.0 window:focus-pane-on-right (atom-pane.pane.active)
     -0:15.7.0 vim-mode-plus:move-down (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
atom-dark-fusion-syntax 2.0.3 
atom-elixir 0.2.2 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-mdtoc 0.8.3 
atom-ternjs 0.18.2 
atomatigit 1.5.5 
autocomplete-bibtex 0.7.0 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.60 
autoupdate-packages 1.3.1 
blame 0.10.2 
build 0.67.0 
build-cargo 2.0.0 
busy 0.7.0 
color-picker 2.2.5 
docblockr 0.9.1 
easy-motion-redux 1.1.1 
environment 1.3.1 
ex-mode 0.13.1 
expand-region 0.2.6 
expose 0.14.0 
file-icons 2.0.17 
fixmyjs 1.4.1 
git-history 3.2.0 
git-plus 7.3.3 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.12.0 
iex 0.10.0 
ink 0.6.4 
javascript-snippets 1.2.1 
julia-client 0.5.12 
language-diff 0.7.0 
language-elixir 0.17.0 
language-julia 0.10.0 
language-latex 1.0.0 
language-rust 0.4.9 
latex 0.42.3 
latex-completions 0.3.2 
latexer 0.3.0 
lines 0.13.1 
linter 1.11.23 
linter-clojure 1.1.2 
linter-elixirc 1.3.0 
linter-eslint 8.1.3 
linter-flake8 2.1.4 
linter-jshint 3.0.3 
linter-markdown 3.1.0 
linter-rust 0.7.2 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.4 
maximize-panes 0.2.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
move-panes 0.2.0 
nucleus-dark-ui 0.11.0 
Parinfer 1.17.0 
pdf-view 0.55.0 
platformio-ide-terminal 2.4.0 
project-plus 0.9.0 
proto-repl 1.4.16 
proton-mode 0.14.1 
python-isort 0.0.7 
python-tools 0.6.9 
python-yapf 0.13.0 
racer 0.20.0 
react 0.16.2 
react-snippets 0.7.1 
recent-files-fuzzy-finder 0.3.0 
relative-numbers 0.7.1 
release-notes 0.53.0 
tab-switcher 1.5.4 
theme-switch 0.4.0 
vim-mode-plus 0.83.0 
vim-mode-plus-ex-mode 0.9.0 
zentabs 0.8.8 
```

**Comment by leny** [comment]
Hi, thanks for the reporting. 

I'm not an active user of Atom anymore (switched to vim a few months ago), but, for now, I'm mostly too busy with professional work and deadlines to be able to fix this package before a few months.

If anyone of you want to become a collaborator and do the work, I will be happy to include this person(s) on the collaborators list of the package.

Thanks :)

**Comment by wabilin** [comment]
Fixed :v:
