### ISSUE TITLE
Failed to activate the easy-motion-redux package

### ISSUE THREAD

**Issue by damaru2** [leny/atom-easy-motion-redux#22]
[Enter steps to reproduce:]

1. Open atom
2. Done

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Ubuntu 14.04.5
**Thrown From**: [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux) package 1.1.1

### Stack Trace

Failed to activate the easy-motion-redux package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/opt/atom/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/opt/atom/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Package.module.exports.Package.activateKeymaps (/opt/atom/resources/app/src/package.js:374:38)
    at Package.module.exports.Package.activateResources (/opt/atom/resources/app/src/package.js:341:20)
    at /opt/atom/resources/app/src/package.js:221:29
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at /opt/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:645:40)
    at /opt/atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:603:52)
    at /opt/atom/resources/app/src/atom-environment.js:846:34
```

### Commands

```
```

### Non-Core Packages

```
atom-clang 1.0.14 
atom-debugger 0.1.6 
atom-keyboard-macros-vim 0.1.6 
autocomplete-java 1.2.7 
autocomplete-python 1.9.0 
busy-signal 1.4.3 
clip-history 0.4.0 
clipboard-plus 0.5.1 
cursor-history 0.11.1 
easy-motion-redux 1.1.1 
ex-mode 0.15.0 
Hydrogen 1.18.0 
intentions 1.1.2 
java-importer 1.4.1 
language-latex 1.0.0 
latex 0.44.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.2 
latex-plus 0.9.1 
linter 2.2.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-spell-latex 0.9.2 
linter-ui-default 1.6.2 
markdown-preview-plus 2.4.9 
persistent-undo 1.2.0 
python-indent 1.0.3 
python-tools 0.6.9 
undo-tree 0.2.0 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 0.93.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by wabilin** [comment]
Hi @damaru2 
Do you still get this problem?

**Comment by damaru2** [comment]
I stopped using atom, but I just opened it and it is not happening anymore after upgrading the package

**Comment by wabilin** [comment]
Thanks for your reply :)
