### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by trcook** [leny/atom-easy-motion-redux#4]
[Enter steps to reproduce below:]
1. run 'easy-motion-redux:letter' via key command (for me this is `cmd-;`)
2. type anything. 

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.5
**Thrown From**: [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/tom/.atom/packages/easy-motion-redux/lib/views/input.js:149

TypeError: Cannot read property '0' of undefined
    at InputView.confirm (/Users/tom/.atom/packages/easy-motion-redux/lib/views/input.js:149:74)
    at InputView.filterPositions (/Users/tom/.atom/packages/easy-motion-redux/lib/views/input.js:167:18)
    at InputView.autosubmit (/Users/tom/.atom/packages/easy-motion-redux/lib/views/input.js:116:14)
```
### Commands

```
     -0:46.1.0 jumpy:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:43.8.0 jumpy:e (atom-text-editor.editor.vim-mode.insert-mode.is-focused.jumpy-jump-mode)
     -0:43.8.0 jumpy:m (atom-text-editor.editor.vim-mode.insert-mode.is-focused.jumpy-jump-mode)
  2x -0:41.9.0 pane:show-next-item (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:33.7.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:32.9.0 atomic-emacs:previous-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:32.2.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:31.5.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:30.5.0 pane:show-next-item (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:20.8.0 easy-motion-redux:letter (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:19.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.5.0 easy-motion-redux:letter (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:09.4.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:08.6.0 easy-motion-redux:letter (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "projectHome": "/Users/tom/Documents/Projects",
    "disabledPackages": [
      "open-terminal-here",
      "language-julia",
      "language-jade"
    ],
    "packagesWithKeymapsDisabled": [
      "atomic-emacs",
      "vim-mode",
      "python-autopep8"
    ]
  },
  "easy-motion-redux": {
    "replaceCharacters": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  }
}
```
### Installed Packages

``` coffee
# User
atomic-emacs, v0.7.4
autocomplete-paths, v1.0.2
build-tools, v4.3.1
custom-title, v1.0.1
easy-motion-redux, v1.0.0
jumpy, v2.0.10
language-latex, v0.6.1
language-r, v0.4.0
latex, v0.28.2
linter, v1.11.2
linter-pylint, v1.0.4
minimap, v4.16.1
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.5
minimap-git-diff, v4.1.8
project-manager, v2.6.5
python-autopep8, v0.1.3
vim-mode, v0.63.0
wordcount, v2.4.1

# Dev
No dev packages
```

**Comment by trcook** [comment]
Closing file and reopening seemed to fix issue. Looks idiosyncratic -- probably no need to investigate.

**Comment by leny** [comment]
Ok, keep me in touch in case of reproducing. :+1:

**Comment by gregrobson** [comment]
I get this issue when after activating "easy motion mode" I hit enter.

I use this to navigate to the end of a chosen line (i.e. choosing the line break character).

It would be awesome if this could be added in :+1: 

Edit: I'm on Windows!

**Comment by DXist** [comment]
I reproduce on Python and Golang sources.

I get following stack trace:

```
TypeError: Cannot read property '0' of undefined
    at InputView.confirm (/Users/rinatshigapov/.atom/packages/easy-motion-redux/lib/views/input.js:150:41)
    at atom-text-editor.coreConfirm (/Users/rinatshigapov/.atom/packages/easy-motion-redux/lib/views/input.js:73:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by swt30** [comment]
I have this too for Markdown source.
