### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class

### ISSUE THREAD

**Issue by obenjiro** [leny/atom-easy-motion-redux#9]
[Enter steps to reproduce below:]
1. Open letter jump
2. Type [

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux) package, v1.0.0
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class

```
At /Users/12/.atom/packages/easy-motion-redux/lib/views/input.js:260

SyntaxError: Invalid regular expression: /[/: Unterminated character class
    at new RegExp (native)
    at InputView.loadPositions (/Users/12/.atom/packages/easy-motion-redux/lib/views/input.js:260:35)
    at InputView.autosubmit (/Users/12/.atom/packages/easy-motion-redux/lib/views/input.js:111:18)
```
### Commands

```
     -2:04.0 tabs:keep-preview-tab (atom-text-editor.editor)
     -1:07.5.0 nuclide-quick-open:find-anything-via-omni-search (atom-text-editor.editor.is-focused)
     -1:06.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:04.0 tabs:keep-preview-tab (atom-text-editor.editor)
     -0:39.2.0 easy-motion-redux:letter (atom-text-editor.editor.is-focused)
  2x -0:35.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:28.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:28.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:09.9.0 spell-check:correct-misspelling (atom-text-editor.editor.is-focused)
     -0:07.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:06.4.0 easy-motion-redux:letter (atom-text-editor.editor.is-focused)
     -0:02.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-terminal-panel, v4.4.4
build, v0.57.0
build-grunt, v0.4.0
docblockr, v0.7.3
easy-motion-redux, v1.0.0
editorconfig, v1.2.4
environment, v1.2.0
file-icons, v1.6.19
js-hyperclick, v1.4.1
minimap, v4.21.0
nuclide, v0.126.0
project-plus, v0.8.0

# Dev
No dev packages
```

**Comment by leny** [comment]
Thanks for the report.

Fixed & published as `1.0.1`.
